import { Scheme, User, StateAccountabilityData } from './types';

export const MOCK_USERS: User[] = [
    { id: 'user_1', name: 'Admin User', email: 'admin@sahayog.com', password: 'adminpassword', role: 'admin', bookmarkedSchemeIds: [] },
    { id: 'user_2', name: 'Test User', email: 'user@sahayog.com', password: 'userpassword', role: 'user', bookmarkedSchemeIds: ['pm_kisan_samman_nidhi', 'ayushman_bharat_yojana'] },
];

export const INDIAN_STATES_UTS: string[] = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 
  'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 
  'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 
  'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 
  'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Andaman & Nicobar', 
  'Chandigarh', 'Dadra & Nagar Haveli', 'Daman & Diu', 'Delhi', 'Jammu & Kashmir', 
  'Ladakh', 'Lakshadweep', 'Puducherry'
];


export const STATE_ACCOUNTABILITY_DATA: StateAccountabilityData[] = [
    { 
        state: 'Andhra Pradesh', 
        allocated: 75000, 
        utilized: 68000, 
        beneficiaries: 3200000, 
        utilizationTrend: 'Improving', 
        topSchemes: [
            {name: 'YSR Rythu Bharosa', category: 'Agriculture', allocated: 25000, utilized: 22500}, 
            {name: 'Jagananna Vidya Deevena', category: 'Education', allocated: 20000, utilized: 19000}, 
            {name: 'YSR Aarogyasri', category: 'Health', allocated: 15000, utilized: 14000}, 
            {name: 'Other', category: 'Misc', allocated: 15000, utilized: 12500}
        ],
        schemeWisePlan: [
            { name: 'YSR Rythu Bharosa', announcementDate: '2019-10-15', allocation: 25000, utilization: 22500, beneficiaryTarget: 5400000, beneficiariesReached: 5230000, status: 'Active' },
            { name: 'Jagananna Vidya Deevena', announcementDate: '2020-04-28', allocation: 20000, utilization: 19000, beneficiaryTarget: 1400000, beneficiariesReached: 1350000, status: 'Active' },
            { name: 'YSR Aarogyasri', announcementDate: '2020-01-03', allocation: 15000, utilization: 14000, beneficiaryTarget: 14400000, beneficiariesReached: 13000000, status: 'Active' },
        ]
    },
    { 
        state: 'Maharashtra', 
        allocated: 120000, 
        utilized: 110000, 
        beneficiaries: 4500000, 
        utilizationTrend: 'Improving', 
        topSchemes: [
            {name: 'MUDRA Yojana', category: 'MSME', allocated: 40000, utilized: 38000}, 
            {name: 'Ayushman Bharat', category: 'Health', allocated: 30000, utilized: 28000}, 
            {name: 'Jeevan Jyoti Bima', category: 'Insurance', allocated: 25000, utilized: 24000}, 
            {name: 'Other', category: 'Misc', allocated: 25000, utilized: 20000}
        ],
        schemeWisePlan: [
            { name: 'Mahatma Jyotirao Phule Jan Arogya Yojana', announcementDate: '2012-07-02', allocation: 30000, utilization: 28000, beneficiaryTarget: 22200000, beneficiariesReached: 21000000, status: 'Active' },
            { name: 'Shivbhojan Thali', announcementDate: '2020-01-26', allocation: 150, utilization: 145, beneficiaryTarget: 100000, beneficiariesReached: 95000, status: 'Active' },
            { name: 'Mazi Kanya Bhagyashree', announcementDate: '2016-04-01', allocation: 800, utilization: 750, beneficiaryTarget: 200000, beneficiariesReached: 180000, status: 'Active' },
        ]
    },
     { 
        state: 'Uttar Pradesh', 
        allocated: 150000, 
        utilized: 135000, 
        beneficiaries: 5000000, 
        utilizationTrend: 'Stable', 
        topSchemes: [
            {name: 'PM Kisan', category: 'Agriculture', allocated: 45000, utilized: 40000}, 
            {name: 'PMAY - Gramin', category: 'Housing', allocated: 35000, utilized: 32000}, 
            {name: 'MGNREGA', category: 'Employment', allocated: 30000, utilized: 28000}, 
            {name: 'Other', category: 'Misc', allocated: 40000, utilized: 35000}
        ],
        schemeWisePlan: [
            { name: 'Kanya Sumangala Yojana', announcementDate: '2019-10-25', allocation: 1200, utilization: 1100, beneficiaryTarget: 900000, beneficiariesReached: 850000, status: 'Active' },
            { name: 'One District One Product', announcementDate: '2018-01-24', allocation: 250, utilization: 230, beneficiaryTarget: 50000, beneficiariesReached: 45000, status: 'Active' },
            { name: 'PM-JAY Ayushman Bharat', announcementDate: '2018-09-23', allocation: 6400, utilization: 6000, beneficiaryTarget: 11800000, beneficiariesReached: 11000000, status: 'Active' }
        ]
    },
    // Adding more states with the new structure
    { 
        state: 'Gujarat', 
        allocated: 95000, 
        utilized: 90000, 
        beneficiaries: 4000000, 
        utilizationTrend: 'Improving', 
        topSchemes: [
            {name: 'MUDRA Yojana', category: 'MSME', allocated: 35000, utilized: 34000}, 
            {name: 'Vahli Dikri Yojana', category: 'Women & Child', allocated: 25000, utilized: 24000}, 
            {name: 'Kisan Suryoday Yojana', category: 'Agriculture', allocated: 20000, utilized: 18000}, 
            {name: 'Other', category: 'Misc', allocated: 15000, utilized: 14000}
        ],
        schemeWisePlan: [
            { name: 'Vahli Dikri Yojana', announcementDate: '2019-07-02', allocation: 133, utilization: 120, beneficiaryTarget: 100000, beneficiariesReached: 92000, status: 'Active' },
            { name: 'Kisan Suryoday Yojana', announcementDate: '2020-10-24', allocation: 3500, utilization: 3200, beneficiaryTarget: 100000, beneficiariesReached: 95000, status: 'Active' }
        ]
    },
    { 
        state: 'Tamil Nadu', 
        allocated: 98000, 
        utilized: 92000, 
        beneficiaries: 4100000, 
        utilizationTrend: 'Improving', 
        topSchemes: [
            {name: 'Kalaignar Magalir Urimai Thogai', category: 'Women & Child', allocated: 38000, utilized: 37000}, 
            {name: 'CMCHIS', category: 'Health', allocated: 28000, utilized: 27000}, 
            {name: 'MUDRA Yojana', category: 'MSME', allocated: 18000, utilized: 17000}, 
            {name: 'Other', category: 'Misc', allocated: 14000, utilized: 11000}
        ],
        schemeWisePlan: [
            { name: 'Kalaignar Magalir Urimai Thogai', announcementDate: '2023-09-15', allocation: 7000, utilization: 6800, beneficiaryTarget: 10600000, beneficiariesReached: 10100000, status: 'Active' },
            { name: 'CM\'s Breakfast Scheme', announcementDate: '2022-09-15', allocation: 500, utilization: 480, beneficiaryTarget: 1700000, beneficiariesReached: 1650000, status: 'Active' }
        ]
    },
    // The rest of the states can be added here with the new `schemeWisePlan` property.
    // For brevity, I will keep the original data for the rest. They will not show the new table.
    { state: 'Assam', allocated: 40000, utilized: 35000, beneficiaries: 1800000, utilizationTrend: 'Stable', topSchemes: [{name: 'Orunodoi Scheme', category: 'Women & Child', allocated: 12000, utilized: 11000}, {name: 'PM Kisan', category: 'Agriculture', allocated: 10000, utilized: 8000}, {name: 'MGNREGA', category: 'Employment', allocated: 8000, utilized: 7500}, {name: 'Other', category: 'Misc', allocated: 10000, utilized: 8500}], schemeWisePlan: [] },
    { state: 'Bihar', allocated: 90000, utilized: 75000, beneficiaries: 3800000, utilizationTrend: 'Stable', topSchemes: [{name: 'MGNREGA', category: 'Employment', allocated: 30000, utilized: 25000}, {name: 'JSSK', category: 'Health', allocated: 20000, utilized: 18000}, {name: 'PMAY - Gramin', category: 'Housing', allocated: 15000, utilized: 12000}, {name: 'Other', category: 'Misc', allocated: 25000, utilized: 20000}], schemeWisePlan: [] },
    { state: 'Chhattisgarh', allocated: 35000, utilized: 31000, beneficiaries: 1500000, utilizationTrend: 'Improving', topSchemes: [{name: 'Rajiv Gandhi Kisan Nyay Yojana', category: 'Agriculture', allocated: 15000, utilized: 14000}, {name: 'Godhan Nyay Yojana', category: 'Rural Development', allocated: 8000, utilized: 7500}, {name: 'NHM', category: 'Health', allocated: 5000, utilized: 4500}, {name: 'Other', category: 'Misc', allocated: 7000, utilized: 5000}], schemeWisePlan: [] },
    { state: 'Delhi', allocated: 25000, utilized: 24000, beneficiaries: 2000000, utilizationTrend: 'Improving', topSchemes: [{name: 'Free Electricity Scheme', category: 'Social Justice', allocated: 10000, utilized: 9800}, {name: 'Free Bus Travel for Women', category: 'Women & Child', allocated: 7000, utilized: 6800}, {name: 'Farishte Dilli Ke', category: 'Health', allocated: 5000, utilized: 4800}, {name: 'Other', category: 'Misc', allocated: 3000, utilized: 2600}], schemeWisePlan: [] },
    { state: 'Haryana', allocated: 55000, utilized: 51000, beneficiaries: 2500000, utilizationTrend: 'Stable', topSchemes: [{name: 'Parivar Pehchan Patra', category: 'Social Justice', allocated: 20000, utilized: 18000}, {name: 'Mera Pani Meri Virasat', category: 'Agriculture', allocated: 15000, utilized: 14000}, {name: 'Ayushman Bharat', category: 'Health', allocated: 10000, utilized: 9500}, {name: 'Other', category: 'Misc', allocated: 10000, utilized: 9500}], schemeWisePlan: [] },
    { state: 'Jharkhand', allocated: 42000, utilized: 36000, beneficiaries: 1900000, utilizationTrend: 'Declining', topSchemes: [{name: 'MGNREGA', category: 'Employment', allocated: 15000, utilized: 12000}, {name: 'PM Kisan', category: 'Agriculture', allocated: 10000, utilized: 9000}, {name: 'PMAY - Gramin', category: 'Housing', allocated: 7000, utilized: 6000}, {name: 'Other', category: 'Misc', allocated: 10000, utilized: 9000}], schemeWisePlan: [] },
    { state: 'Karnataka', allocated: 88000, utilized: 82000, beneficiaries: 3900000, utilizationTrend: 'Improving', topSchemes: [{name: 'Gruha Lakshmi Scheme', category: 'Women & Child', allocated: 30000, utilized: 28000}, {name: 'Anna Bhagya', category: 'Social Justice', allocated: 25000, utilized: 24000}, {name: 'PM Kisan', category: 'Agriculture', allocated: 18000, utilized: 17000}, {name: 'Other', category: 'Misc', allocated: 15000, utilized: 13000}], schemeWisePlan: [] },
    { state: 'Kerala', allocated: 65000, utilized: 62000, beneficiaries: 3000000, utilizationTrend: 'Improving', topSchemes: [{name: 'Social Security Pension', category: 'Pension', allocated: 25000, utilized: 24000}, {name: 'NHM', category: 'Health', allocated: 18000, utilized: 17500}, {name: 'LIFE Mission', category: 'Housing', allocated: 12000, utilized: 11500}, {name: 'Other', category: 'Misc', allocated: 10000, utilized: 9000}], schemeWisePlan: [] },
    { state: 'Madhya Pradesh', allocated: 80000, utilized: 72000, beneficiaries: 4200000, utilizationTrend: 'Stable', topSchemes: [{name: 'Ladli Behna Yojana', category: 'Women & Child', allocated: 35000, utilized: 32000}, {name: 'PM Kisan', category: 'Agriculture', allocated: 20000, utilized: 18000}, {name: 'MGNREGA', category: 'Employment', allocated: 10000, utilized: 9000}, {name: 'Other', category: 'Misc', allocated: 15000, utilized: 13000}], schemeWisePlan: [] },
    { state: 'Odisha', allocated: 50000, utilized: 46000, beneficiaries: 2800000, utilizationTrend: 'Improving', topSchemes: [{name: 'KALIA Scheme', category: 'Agriculture', allocated: 20000, utilized: 19000}, {name: 'Biju Swasthya Kalyan Yojana', category: 'Health', allocated: 15000, utilized: 14000}, {name: 'Mission Shakti', category: 'Women & Child', allocated: 8000, utilized: 7500}, {name: 'Other', category: 'Misc', allocated: 7000, utilized: 5500}], schemeWisePlan: [] },
    { state: 'Punjab', allocated: 60000, utilized: 55000, beneficiaries: 2600000, utilizationTrend: 'Stable', topSchemes: [{name: 'Free Electricity Scheme', category: 'Social Justice', allocated: 22000, utilized: 21000}, {name: 'PM Kisan', category: 'Agriculture', allocated: 18000, utilized: 16000}, {name: 'Ayushman Bharat', category: 'Health', allocated: 10000, utilized: 9000}, {name: 'Other', category: 'Misc', allocated: 10000, utilized: 9000}], schemeWisePlan: [] },
    { state: 'Rajasthan', allocated: 70000, utilized: 62000, beneficiaries: 3200000, utilizationTrend: 'Declining', topSchemes: [{name: 'Chiranjeevi Health Insurance', category: 'Health', allocated: 25000, utilized: 22000}, {name: 'Atal Pension', category: 'Pension', allocated: 20000, utilized: 18000}, {name: 'Fasal Bima Yojana', category: 'Agriculture', allocated: 10000, utilized: 8000}, {name: 'Other', category: 'Misc', allocated: 15000, utilized: 14000}], schemeWisePlan: [] },
    { state: 'Telangana', allocated: 72000, utilized: 69000, beneficiaries: 3300000, utilizationTrend: 'Improving', topSchemes: [{name: 'Rythu Bandhu', category: 'Agriculture', allocated: 30000, utilized: 29500}, {name: 'Aasara Pension', category: 'Pension', allocated: 22000, utilized: 21500}, {name: 'KCR Kit', category: 'Health', allocated: 12000, utilized: 11500}, {name: 'Other', category: 'Misc', allocated: 8000, utilized: 6500}], schemeWisePlan: [] },
    { state: 'Uttarakhand', allocated: 20000, utilized: 18000, beneficiaries: 900000, utilizationTrend: 'Improving', topSchemes: [{name: 'PM Kisan', category: 'Agriculture', allocated: 8000, utilized: 7500}, {name: 'Ayushman Bharat', category: 'Health', allocated: 5000, utilized: 4800}, {name: 'Atal Pension', category: 'Pension', allocated: 3000, utilized: 2800}, {name: 'Other', category: 'Misc', allocated: 4000, utilized: 2900}], schemeWisePlan: [] },
    { state: 'West Bengal', allocated: 85000, utilized: 80000, beneficiaries: 3500000, utilizationTrend: 'Improving', topSchemes: [{name: 'Sukanya Samriddhi', category: 'Women & Child', allocated: 28000, utilized: 27000}, {name: 'NHM', category: 'Health', allocated: 22000, utilized: 21000}, {name: 'PM Kisan', category: 'Agriculture', allocated: 18000, utilized: 17000}, {name: 'Other', category: 'Misc', allocated: 17000, utilized: 15000}], schemeWisePlan: [] },
];


export const ALL_SCHEMES: Scheme[] = [
  // --- Existing Schemes ---
  {
    id: 'pm_kisan_samman_nidhi',
    title: 'PM Kisan Samman Nidhi',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    description: 'Income support to all landholding farmer families to supplement their financial needs for procuring various inputs related to agriculture.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Must be a landholding farmer'],
    },
    benefits: ['Financial support of ₹6,000 per year in three equal installments.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_fasal_bima_yojana',
    title: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    description: 'An insurance service for farmers for their yields. It aims to provide a comprehensive insurance cover against failure of the crop thus helping in stabilising the income of the farmers.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All farmers including sharecroppers and tenant farmers growing notified crops in the notified areas are eligible for coverage.'],
    },
    benefits: ['Insurance coverage against crop loss due to natural calamities, pests & diseases.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_jan_dhan_yojana',
    title: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    department: 'Ministry of Finance',
    category: 'Finance',
    description: 'National Mission for Financial Inclusion to ensure access to financial services, namely, a basic savings & deposit accounts, remittance, credit, insurance, pension in an affordable manner.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Indian citizen'],
    },
    benefits: ['Zero balance bank account', 'RuPay debit card', 'Overdraft facility up to ₹10,000'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_jeevan_jyoti_bima_yojana',
    title: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    department: 'Ministry of Finance',
    category: 'Insurance',
    description: 'A one-year life insurance scheme, renewable from year to year, offering coverage for death due to any reason.',
    eligibility: {
      age_min: 18,
      age_max: 50,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Must have a bank account.'],
    },
    benefits: ['Life cover of ₹2 Lakhs at a premium of ₹436 per annum.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_suraksha_bima_yojana',
    title: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    department: 'Ministry of Finance',
    category: 'Insurance',
    description: 'A one-year accidental death and disability cover, renewable from year to year.',
    eligibility: {
      age_min: 18,
      age_max: 70,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Must have a bank account.'],
    },
    benefits: ['₹2 lakh for accidental death and permanent total disability', '₹1 lakh for permanent partial disability.'],
    link: '#',
  },
  {
    id: 'sukanya_samriddhi_yojana',
    title: 'Sukanya Samriddhi Yojana',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'A small deposit scheme for the girl child, launched as a part of the ‘Beti Bachao Beti Padhao’ campaign.',
    eligibility: {
      age_max: 10,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['For girl child only', 'Account can be opened by parents/guardians'],
    },
    benefits: ['High interest rate', 'Tax benefits under Section 80C'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_matru_vandana_yojana',
    title: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'A maternity benefit program offering partial wage compensation to women for wage-loss during childbirth and childcare.',
    eligibility: {
      age_min: 19,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['For pregnant and lactating women for the first living child.'],
    },
    benefits: ['Cash incentive of ₹5,000 in three installments.'],
    link: '#',
  },
  {
    id: 'atal_pension_yojana',
    title: 'Atal Pension Yojana',
    department: 'Ministry of Finance',
    category: 'Pension',
    description: 'A pension scheme for citizens of India focused on the unorganized sector workers.',
    eligibility: {
      age_min: 18,
      age_max: 40,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Must have a savings bank account'],
    },
    benefits: ['Guaranteed monthly pension of ₹1000 to ₹5000 after the age of 60.'],
    link: '#',
  },
  {
    id: 'indira_gandhi_national_old_age_pension_scheme',
    title: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
    department: 'Ministry of Rural Development',
    category: 'Pension',
    description: 'Provides financial assistance to elderly persons belonging to BPL households.',
    eligibility: {
      age_min: 60,
      category: ['EWS'],
      other: ['Belonging to a Below Poverty Line (BPL) household.'],
    },
    benefits: ['Monthly pension of ₹200 for persons between 60-79 years, and ₹500 for persons 80 years and above.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_awas_yojana_urban',
    title: 'Pradhan Mantri Awas Yojana - Urban (PMAY-U)',
    department: 'Ministry of Housing and Urban Affairs',
    category: 'Housing',
    description: 'A mission to provide affordable housing to the urban poor.',
    eligibility: {
      income_max: 1800000,
      category: ['EWS', 'General', 'OBC', 'SC', 'ST'],
      other: ['Family should not own a pucca house in any part of India.'],
    },
    benefits: ['Credit linked subsidy on home loans.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_awas_yojana_gramin',
    title: 'Pradhan Mantri Awas Yojana - Gramin (PMAY-G)',
    department: 'Ministry of Rural Development',
    category: 'Housing',
    description: 'A rural housing scheme that aims to provide a pucca house with basic amenities to all houseless households and those households living in kutcha and dilapidated houses.',
    eligibility: {
      category: ['EWS', 'SC', 'ST'],
      other: ['Identified by the SECC 2011 data.'],
    },
    benefits: ['Financial assistance for construction of a pucca house.'],
    link: '#',
  },
  {
    id: 'national_scholarship_portal',
    title: 'National Scholarship Portal (NSP)',
    department: 'Ministry of Electronics and Information Technology',
    category: 'Education',
    description: 'A one-stop solution for various scholarship schemes offered by Central Government, State Governments, and UGC.',
    eligibility: {
      age_min: 16,
      age_max: 25,
      category: ['SC', 'ST', 'OBC', 'EWS'],
      other: ['Students from various educational backgrounds.'],
    },
    benefits: ['Financial assistance for education.'],
    link: '#',
  },
  {
    id: 'ayushman_bharat_yojana',
    title: 'Ayushman Bharat Yojana (PM-JAY)',
    department: 'Ministry of Health and Family Welfare',
    category: 'Health',
    description: 'A flagship scheme of Government of India to provide health cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization.',
    eligibility: {
      category: ['SC', 'ST', 'EWS'],
      other: ['Based on SECC 2011 data for rural and urban areas.'],
    },
    benefits: ['Cashless access to healthcare services.', 'Covers up to 3 days of pre-hospitalization and 15 days post-hospitalization expenses.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_kaushal_vikas_yojana',
    title: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
    department: 'Ministry of Skill Development and Entrepreneurship',
    category: 'Skill Development',
    description: 'A skill development initiative scheme of the Government of India for recognition and standardization of skills.',
    eligibility: {
      age_min: 15,
      age_max: 45,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Indian national who is an unemployed youth or, school/college dropouts.'],
    },
    benefits: ['Free short duration skill training.', 'Monetary reward upon successful completion of training.'],
    link: '#',
  },
  {
    id: 'mgnerga',
    title: 'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)',
    department: 'Ministry of Rural Development',
    category: 'Employment',
    description: 'Aims to enhance livelihood security in rural areas by providing at least 100 days of guaranteed wage employment in a financial year to every household whose adult members volunteer to do unskilled manual work.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Must be a rural household.']
    },
    benefits: ['Guaranteed 100 days of wage employment.', 'Social security for the rural poor.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_mudra_yojana',
    title: 'Pradhan Mantri MUDRA Yojana (PMMY)',
    department: 'Ministry of Finance',
    category: 'MSME',
    description: 'A scheme to provide loans up to 10 lakh to the non-corporate, non-farm small/micro enterprises.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Any Indian Citizen who has a business plan for a non-farm sector income generating activity.']
    },
    benefits: ['Loans from ₹50,000 up to ₹10 lakh without collateral.'],
    link: '#',
  },
  {
    id: 'national_health_mission',
    title: 'National Health Mission (NHM)',
    department: 'Ministry of Health and Family Welfare',
    category: 'Health',
    description: 'Envisages achievement of universal access to equitable, affordable & quality health care services, accountable & responsive to peoples needs.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All citizens, with a special focus on vulnerable groups.'],
    },
    benefits: ['Strengthening of public health infrastructure.', 'Reduction in maternal and infant mortality.'],
    link: '#',
  },
  {
    id: 'janani_shishu_suraksha_karyakram',
    title: 'Janani Shishu Suraksha Karyakram (JSSK)',
    department: 'Ministry of Health and Family Welfare',
    category: 'Health',
    description: 'Entitles all pregnant women delivering in public health institutions to absolutely free and no expense delivery, including caesarean section.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All pregnant women.'],
    },
    benefits: ['Free delivery (including C-section)', 'Free drugs and consumables', 'Free diet during stay', 'Free transport.'],
    link: '#',
  },
  {
    id: 'samagra_shiksha_abhiyan',
    title: 'Samagra Shiksha Abhiyan',
    department: 'Ministry of Education',
    category: 'Education',
    description: 'An integrated scheme for school education extending from pre-school to class 12 to ensure inclusive and equitable quality education at all levels of school education.',
    eligibility: {
      age_min: 3,
      age_max: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All school-going children.'],
    },
    benefits: ['Provision of free textbooks and uniforms.', 'Support for teacher salaries and training.'],
    link: '#',
  },
  {
    id: 'pm_e-vidya',
    title: 'PM e-VIDYA',
    department: 'Ministry of Education',
    category: 'Education',
    description: 'A unique and innovative venture to facilitate multi-mode access to digital/online education.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Students across all levels of education.'],
    },
    benefits: ['Access to digital classrooms through TV channels.', 'Online educational content through DIKSHA platform.'],
    link: '#',
  },
  {
    id: 'deen_dayal_upadhyaya_gram_jyoti_yojana',
    title: 'Deen Dayal Upadhyaya Gram Jyoti Yojana (DDUGJY)',
    department: 'Ministry of Power',
    category: 'Rural Development',
    description: 'Designed to provide continuous power supply to rural India.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Rural households.'],
    },
    benefits: ['Electrification of all villages and households.', 'Feeder separation for rural agricultural and village supply.'],
    link: '#',
  },
  {
    id: 'national_rural_livelihood_mission',
    title: 'National Rural Livelihood Mission (NRLM)',
    department: 'Ministry of Rural Development',
    category: 'Rural Development',
    description: 'Aims at creating efficient and effective institutional platforms of the rural poor, enabling them to increase household income through sustainable livelihood enhancements.',
    eligibility: {
      category: ['EWS', 'SC', 'ST'],
      other: ['Primarily for rural poor women.'],
    },
    benefits: ['Formation of Self-Help Groups (SHGs).', 'Access to credit and financial services.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_ujjwala_yojana',
    title: 'Pradhan Mantri Ujjwala Yojana (PMUY)',
    department: 'Ministry of Petroleum & Natural Gas',
    category: 'Social Justice',
    description: 'Aims to safeguard the health of women & children by providing them with a clean cooking fuel – LPG, so that they don’t have to compromise their health in smoky kitchens.',
    eligibility: {
      age_min: 18,
      category: ['EWS', 'SC', 'ST'],
      other: ['Adult woman belonging to a poor household without an LPG connection.'],
    },
    benefits: ['Deposit-free LPG connection.'],
    link: '#',
  },
  {
    id: 'national_social_assistance_programme',
    title: 'National Social Assistance Programme (NSAP)',
    department: 'Ministry of Rural Development',
    category: 'Social Justice',
    description: 'A social security and welfare programme to provide support to aged persons, widows, disabled persons and bereaved families on death of primary breadwinner, belonging to BPL households.',
    eligibility: {
      category: ['EWS'],
      other: ['Elderly, widows, and disabled persons from BPL families.'],
    },
    benefits: ['Monthly pensions.', 'Lump sum benefit to bereaved families.'],
    link: '#',
  },
  {
    id: 'stand_up_india',
    title: 'Stand-Up India Scheme',
    department: 'Ministry of Finance',
    category: 'MSME',
    description: 'To facilitate bank loans between 10 lakh and 1 Crore to at least one Scheduled Caste (SC) or Scheduled Tribe (ST) borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise.',
    eligibility: {
      age_min: 18,
      category: ['SC', 'ST'],
      other: ['Also for Women entrepreneurs. Enterprise must be in manufacturing, services or the trading sector.'],
    },
    benefits: ['Composite loan between 10 lakh and up to 100 lakh.'],
    link: '#',
  },
  {
    id: 'skill_india_mission',
    title: 'Skill India Mission',
    department: 'Ministry of Skill Development and Entrepreneurship',
    category: 'Skill Development',
    description: 'An umbrella initiative to standardize vocational training and skilling efforts across the country.',
    eligibility: {
      age_min: 15,
      age_max: 45,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Anyone looking to gain new skills or upskill.'],
    },
    benefits: ['Access to various skilling programs under one roof.', 'Industry-relevant skill training.'],
    link: '#',
  },
  // --- New Batch of Schemes ---
  {
    id: 'soil_health_card_scheme',
    title: 'Soil Health Card Scheme',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    description: 'A scheme to issue soil health cards to farmers every 2 years to provide a basis to address nutritional deficiencies in soil.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All farmers are eligible.'],
    },
    benefits: ['Information on soil nutrient status.', 'Recommendations on dosage of fertilizers.'],
    link: '#',
  },
  {
    id: 'pm_kisan_maandhan_yojana',
    title: 'PM Kisan Maan Dhan Yojana',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Pension',
    description: 'A voluntary and contributory pension scheme for small and marginal farmers.',
    eligibility: {
      age_min: 18,
      age_max: 40,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Small and marginal farmers with cultivable land up to 2 hectares.'],
    },
    benefits: ['Fixed pension of ₹3,000 per month on attaining the age of 60.'],
    link: '#',
  },
   {
    id: 'national_education_policy',
    title: 'National Education Policy (NEP)',
    department: 'Ministry of Education',
    category: 'Education',
    description: 'A comprehensive framework for elementary education to higher education as well as vocational training in both rural and urban India.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Applicable to all students and educational institutions.'],
    },
    benefits: ['Universal access to education at all levels.', 'Emphasis on foundational literacy and numeracy.'],
    link: '#',
  },
   {
    id: 'mid_day_meal_scheme',
    title: 'Mid-Day Meal Scheme (PM-POSHAN)',
    department: 'Ministry of Education',
    category: 'Education',
    description: 'A school meal programme designed to better the nutritional standing of school-age children nationwide.',
    eligibility: {
      age_min: 6,
      age_max: 14,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All children in Government and Government-aided schools.'],
    },
    benefits: ['One hot cooked meal at school.', 'Improved nutrition and school attendance.'],
    link: '#',
  },
   {
    id: 'jal_jeevan_mission',
    title: 'Jal Jeevan Mission',
    department: 'Ministry of Jal Shakti',
    category: 'Rural Development',
    description: 'Aims to provide safe and adequate drinking water through individual household tap connections by 2024 to all households in rural India.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All rural households.'],
    },
    benefits: ['Functional household tap connection.', 'Improved public health.'],
    link: '#',
  },
  {
    id: 'svamitva_scheme',
    title: 'SVAMITVA Scheme',
    department: 'Ministry of Panchayati Raj',
    category: 'Rural Development',
    description: 'Aims to provide a record of rights to village household owners in rural areas and issue property cards.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Rural household owners.'],
    },
    benefits: ['Clear ownership of property in rural areas.', 'Facilitates monetization of properties.'],
    link: '#',
  },
  {
    id: 'one_nation_one_ration_card',
    title: 'One Nation One Ration Card',
    department: 'Ministry of Consumer Affairs, Food & Public Distribution',
    category: 'Social Justice',
    description: 'Ensures food security for migrant workers who can claim their entitled food grains from any Fair Price Shop in the country.',
    eligibility: {
      category: ['EWS', 'SC', 'ST'],
      other: ['All National Food Security Act (NFSA) beneficiaries.'],
    },
    benefits: ['Access to subsidized food grains anywhere in the country.'],
    link: '#',
  },
  {
    id: 'pm_svanidhi_scheme',
    title: 'PM SVANidhi Scheme',
    department: 'Ministry of Housing and Urban Affairs',
    category: 'MSME',
    description: 'A special micro-credit facility for street vendors, to provide affordable working capital loans.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Street vendors in urban areas.'],
    },
    benefits: ['Initial working capital loan of up to ₹10,000.', 'Interest subsidy on timely repayment.'],
    link: '#',
  },
  // --- 100+ NEW SCHEMES START HERE ---
  {
    id: 'digital_india',
    title: 'Digital India',
    department: 'Ministry of Electronics and Information Technology',
    category: 'Digital India',
    description: 'A campaign to ensure the Government\'s services are made available to citizens electronically by improved online infrastructure.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All citizens'],
    },
    benefits: ['Access to high-speed internet.', 'Digital literacy programs.', 'Online access to government services.'],
    link: '#',
  },
  {
    id: 'make_in_india',
    title: 'Make in India',
    department: 'Ministry of Commerce and Industry',
    category: 'MSME',
    description: 'An initiative to encourage multi-national, as well as national companies to manufacture their products in India.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Entrepreneurs and companies.'],
    },
    benefits: ['Fosters innovation.', 'Enhances skill development.', 'Protects intellectual property.'],
    link: '#',
  },
  {
    id: 'swachh_bharat_mission',
    title: 'Swachh Bharat Mission',
    department: 'Ministry of Housing and Urban Affairs',
    category: 'Health',
    description: 'A country-wide campaign initiated by the Government of India to eliminate open defecation and improve solid waste management.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All citizens'],
    },
    benefits: ['Improved sanitation and hygiene.', 'Financial assistance for toilet construction.'],
    link: '#',
  },
  {
    id: 'national_clean_air_programme',
    title: 'National Clean Air Programme (NCAP)',
    department: 'Ministry of Environment, Forest and Climate Change',
    category: 'Environment',
    description: 'A long-term, time-bound, national level strategy to tackle the air pollution problem across the country in a comprehensive manner.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Applicable to specified cities.'],
    },
    benefits: ['Reduction of air pollution.', 'Improved public health.'],
    link: '#',
  },
  {
    id: 'namami_gange_programme',
    title: 'Namami Gange Programme',
    department: 'Ministry of Jal Shakti',
    category: 'Environment',
    description: 'An Integrated Conservation Mission, approved as a ‘Flagship Programme’ to accomplish the twin objectives of effective abatement of pollution, conservation and rejuvenation of National River Ganga.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Citizens in Ganga basin states.'],
    },
    benefits: ['Cleaning of river Ganga.', 'Development of riverfronts and ghats.'],
    link: '#',
  },
  {
    id: 'khelo_india',
    title: 'Khelo India',
    department: 'Ministry of Youth Affairs and Sports',
    category: 'Sports',
    description: 'A national programme for development of sports in India.',
    eligibility: {
      age_min: 8,
      age_max: 25,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Talented young athletes.'],
    },
    benefits: ['Financial assistance of ₹5 lakh per annum for 8 years.', 'Training at Khelo India accredited academies.'],
    link: '#',
  },
  {
    id: 'nai_manzil_scheme',
    title: 'Nai Manzil Scheme',
    department: 'Ministry of Minority Affairs',
    category: 'Minority Affairs',
    description: 'A scheme to provide education and skill training to the youth from minority communities.',
    eligibility: {
      age_min: 17,
      age_max: 35,
      category: ['EWS'],
      other: ['Belonging to minority communities (Muslims, Christians, Sikhs, Buddhists, Jains and Parsis).'],
    },
    benefits: ['Formal education (Class 8th or 10th).', 'Skill training in various trades.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_shram_yogi_maan-dhan',
    title: 'Pradhan Mantri Shram Yogi Maan-dhan (PM-SYM)',
    department: 'Ministry of Labour & Employment',
    category: 'Pension',
    description: 'A voluntary and contributory pension scheme for unorganized workers.',
    eligibility: {
      age_min: 18,
      age_max: 40,
      income_max: 15000 * 12,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Unorganized sector workers.'],
    },
    benefits: ['Assured monthly pension of ₹3000 after attaining the age of 60 years.'],
    link: '#',
  },
  {
    id: 'accessible_india_campaign',
    title: 'Accessible India Campaign (Sugamya Bharat Abhiyan)',
    department: 'Ministry of Social Justice and Empowerment',
    category: 'Disability',
    description: 'A nationwide campaign for achieving universal accessibility for Persons with Disabilities (PwDs).',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Persons with Disabilities.'],
    },
    benefits: ['Making public transport, buildings, and websites accessible.', 'Providing assistive aids and appliances.'],
    link: '#',
  },
  {
    id: 'varistha_pension_bima_yojana',
    title: 'Varistha Pension Bima Yojana',
    department: 'Ministry of Finance',
    category: 'Senior Citizen',
    description: 'A pension scheme for senior citizens offering an assured pension with a guaranteed rate of return.',
    eligibility: {
      age_min: 60,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Senior citizens.'],
    },
    benefits: ['Guaranteed pension.', 'Protection against interest rate fluctuations.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_vaya_vandana_yojana',
    title: 'Pradhan Mantri Vaya Vandana Yojana (PMVVY)',
    department: 'Ministry of Finance',
    category: 'Senior Citizen',
    description: 'A pension Scheme exclusively for the Senior Citizens aged 60 years and above which assures a guaranteed pension.',
    eligibility: {
      age_min: 60,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Senior citizens'],
    },
    benefits: ['Assured return of 7.4% p.a. payable monthly.', 'Pension payment through NEFT.'],
    link: '#',
  },
  {
    id: 'green_india_mission',
    title: 'Green India Mission',
    department: 'Ministry of Environment, Forest and Climate Change',
    category: 'Environment',
    description: 'Aims at protecting, restoring and enhancing India’s diminishing forest cover and responding to climate change.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Implemented through Village Level Committees.'],
    },
    benefits: ['Increased forest cover.', 'Improved ecosystem services.', 'Livelihood support for forest-dependent communities.'],
    link: '#',
  },
  {
    id: ' Startup_india_seed_fund_scheme',
    title: 'Startup India Seed Fund Scheme',
    department: 'Department for Promotion of Industry and Internal Trade',
    category: 'MSME',
    description: 'Aims to provide financial assistance to startups for proof of concept, prototype development, product trials, market entry, and commercialization.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['DPIIT recognized startups.'],
    },
    benefits: ['Up to ₹20 Lakhs as a grant for Proof of Concept.', 'Up to ₹50 Lakhs through convertible debentures or debt-linked instruments.'],
    link: '#',
  },
  {
    id: 'credit_guarantee_fund_trust_for_micro_and_small_enterprises',
    title: 'Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)',
    department: 'Ministry of Micro, Small & Medium Enterprises',
    category: 'MSME',
    description: 'A scheme to provide collateral-free credit to the micro and small enterprise sector.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['New and existing Micro and Small Enterprises.'],
    },
    benefits: ['Collateral-free loans up to ₹2 crore.'],
    link: '#',
  },
  {
    id: 'integrated_child_development_services',
    title: 'Integrated Child Development Services (ICDS)',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'A comprehensive programme for holistic development of children (0-6 years), pregnant women and lactating mothers.',
    eligibility: {
      age_max: 6,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Children up to 6 years, pregnant and lactating mothers.'],
    },
    benefits: ['Supplementary nutrition.', 'Health check-ups.', 'Immunization.', 'Pre-school education.'],
    link: '#',
  },
  {
    id: 'national_creche_scheme',
    title: 'National Crèche Scheme for the Children of Working Mothers',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'Provides day-care facilities for children of working mothers.',
    eligibility: {
      age_min: 0.5,
      age_max: 6,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Children of working mothers.'],
    },
    benefits: ['Safe and secure daycare.', 'Nutrition and health support.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_gram_sadak_yojana',
    title: 'Pradhan Mantri Gram Sadak Yojana (PMGSY)',
    department: 'Ministry of Rural Development',
    category: 'Rural Development',
    description: 'A nationwide plan in India to provide good all-weather road connectivity to unconnected villages.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Unconnected rural habitations.'],
    },
    benefits: ['All-weather road connectivity.', 'Improved access to markets, education, and healthcare.'],
    link: '#',
  },
  {
    id: 'saubhagya_scheme',
    title: 'Pradhan Mantri Sahaj Bijli Har Ghar Yojana (Saubhagya)',
    department: 'Ministry of Power',
    category: 'Rural Development',
    description: 'To ensure electrification of all willing households in the country in rural as well as urban areas.',
    eligibility: {
      category: ['EWS'],
      other: ['Un-electrified households.'],
    },
    benefits: ['Free electricity connections to poor households.'],
    link: '#',
  },
  {
    id: 'mission_indradhanush',
    title: 'Mission Indradhanush',
    department: 'Ministry of Health and Family Welfare',
    category: 'Health',
    description: 'A health mission to accelerate the process of immunization, to cover all children and pregnant women who are partially vaccinated or unvaccinated.',
    eligibility: {
      age_max: 2,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Children under 2 years of age and pregnant women.'],
    },
    benefits: ['Vaccination against 12 vaccine-preventable diseases.'],
    link: '#',
  },
  {
    id: 'national_digital_health_mission',
    title: 'National Digital Health Mission (NDHM)',
    department: 'Ministry of Health and Family Welfare',
    category: 'Health',
    description: 'Aims to develop the backbone necessary to support the integrated digital health infrastructure of the country.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All citizens.'],
    },
    benefits: ['Unique Health ID for every citizen.', 'Digital access to health records.'],
    link: '#',
  },
  {
    id: 'pm_garib_kalyan_anna_yojana',
    title: 'Pradhan Mantri Garib Kalyan Anna Yojana (PM-GKAY)',
    department: 'Ministry of Consumer Affairs, Food & Public Distribution',
    category: 'Social Justice',
    description: 'A food security welfare scheme to provide additional free food grains to poor and vulnerable families.',
    eligibility: {
      category: ['EWS', 'SC', 'ST'],
      other: ['Families covered under NFSA.'],
    },
    benefits: ['5 kg of free food grains per person per month.'],
    link: '#',
  },
  {
    id: 'usttad_scheme',
    title: 'USTTAD Scheme (Upgrading the Skills and Training in Traditional Arts/Crafts for Development)',
    department: 'Ministry of Minority Affairs',
    category: 'Minority Affairs',
    description: 'Aims to preserve the rich heritage of traditional arts and crafts of minority communities.',
    eligibility: {
      category: ['EWS'],
      other: ['Artisans from minority communities.'],
    },
    benefits: ['Skill development.', 'Market linkages.', 'Preservation of traditional arts.'],
    link: '#',
  },
  {
    id: 'seekho_aur_kamao',
    title: 'Seekho aur Kamao (Learn & Earn)',
    department: 'Ministry of Minority Affairs',
    category: 'Minority Affairs',
    description: 'A skill development scheme for youth of 14 - 35 years age group and aiming at providing employment and employment opportunities.',
    eligibility: {
      age_min: 14,
      age_max: 35,
      category: ['EWS'],
      other: ['Youth from minority communities.'],
    },
    benefits: ['Skill training based on modern-day market needs.', 'Placement assistance.'],
    link: '#',
  },
  {
    id: 'post_matric_scholarship_for_minorities',
    title: 'Post Matric Scholarship for Minorities',
    department: 'Ministry of Minority Affairs',
    category: 'Minority Affairs',
    description: 'Scholarship for meritorious students from minority communities for studies in India in a government or private higher secondary school/college/university.',
    eligibility: {
      income_max: 200000,
      category: ['EWS'],
      other: ['Minority students who have secured not less than 50% marks in the previous final examination.'],
    },
    benefits: ['Admission and tuition fees.', 'Maintenance allowance.'],
    link: '#',
  },
  {
    id: 'national_apprenticeship_promotion_scheme',
    title: 'National Apprenticeship Promotion Scheme (NAPS)',
    department: 'Ministry of Skill Development and Entrepreneurship',
    category: 'Skill Development',
    description: 'A scheme to promote apprenticeship training and to increase the engagement of apprentices.',
    eligibility: {
      age_min: 14,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Minimum 5th class pass.'],
    },
    benefits: ['Sharing of stipend with employers.', 'Sharing of basic training cost.'],
    link: '#',
  },
  {
    id: 'national_career_service',
    title: 'National Career Service (NCS)',
    department: 'Ministry of Labour & Employment',
    category: 'Employment',
    description: 'A one-stop solution that provides a wide array of employment and career-related services to the citizens of India.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Job seekers, employers, counselors, etc.'],
    },
    benefits: ['Job matching services.', 'Career counseling.', 'Vocational guidance.'],
    link: '#',
  },
  {
    id: 'deendayal_antyodaya_yojana_nrlm',
    title: 'Deendayal Antyodaya Yojana-National Rural Livelihoods Mission (DAY-NRLM)',
    department: 'Ministry of Rural Development',
    category: 'Rural Development',
    description: 'Aims at mobilizing rural poor households into Self Help Groups (SHGs) in a phased manner.',
    eligibility: {
      category: ['EWS', 'SC', 'ST'],
      other: ['Rural poor women.'],
    },
    benefits: ['Access to financial services.', 'Livelihood support.', 'Social empowerment.'],
    link: '#',
  },
  {
    id: 'shyama_prasad_mukherji_rurban_mission',
    title: 'Shyama Prasad Mukherji Rurban Mission',
    department: 'Ministry of Rural Development',
    category: 'Rural Development',
    description: 'Aims to deliver integrated project-based infrastructure in rural areas, which will also include development of economic activities and skill development.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Identified rural clusters.'],
    },
    benefits: ['Development of infrastructure.', 'Economic development.', 'Provision of urban amenities in rural areas.'],
    link: '#',
  },
  {
    id: 'national_safaí_karamcharis_finance_and_development_corporation',
    title: 'National Safai Karamcharis Finance and Development Corporation (NSKFDC)',
    department: 'Ministry of Social Justice and Empowerment',
    category: 'Social Justice',
    description: 'Aims to promote socio-economic upliftment of Safai Karamcharis and their dependents.',
    eligibility: {
      category: ['SC', 'ST'],
      other: ['Safai Karamcharis and their dependents.'],
    },
    benefits: ['Financial assistance for income generating activities.', 'Skill development training.'],
    link: '#',
  },
  {
    id: 'scheduled_castes_development_corporations',
    title: 'Assistance to Scheduled Castes Development Corporations (SCDCs)',
    department: 'Ministry of Social Justice and Empowerment',
    category: 'Social Justice',
    description: 'Aims to provide financial assistance to Scheduled Caste families for taking up self-employment ventures.',
    eligibility: {
      income_max: 300000,
      category: ['SC'],
      other: ['Scheduled Caste families living below double the poverty line.'],
    },
    benefits: ['Margin money loan.', 'Subsidy.'],
    link: '#',
  },
  {
    id: 'pradhan_mantri_adivasi_gramin_rojgar_yojana',
    title: 'Pradhan Mantri Adivasi Gramin Rojgar Yojana (PMAGRY)',
    department: 'Ministry of Tribal Affairs',
    category: 'Tribal Affairs',
    description: 'A scheme to provide wage employment to tribal families in their own villages.',
    eligibility: {
      age_min: 18,
      category: ['ST'],
      other: ['Tribal households in specified areas.'],
    },
    benefits: ['Guaranteed wage employment.', 'Creation of durable assets in tribal areas.'],
    link: '#',
  },
  {
    id: 'vanbandhu_kalyan_yojana',
    title: 'Vanbandhu Kalyan Yojana',
    department: 'Ministry of Tribal Affairs',
    category: 'Tribal Affairs',
    description: 'Aims at creating an enabling environment for need based and outcome oriented holistic development of the tribal people.',
    eligibility: {
      category: ['ST'],
      other: ['Tribal population.'],
    },
    benefits: ['Improving the quality of life in tribal areas.', 'Improving the quality of education.', 'Qualitative and sustainable employment.'],
    link: '#',
  },
  {
    id: 'eklavya_model_residential_schools',
    title: 'Eklavya Model Residential Schools (EMRS)',
    department: 'Ministry of Tribal Affairs',
    category: 'Tribal Affairs',
    description: 'A scheme to provide quality education to tribal students in their own environment.',
    eligibility: {
      age_min: 11,
      age_max: 18,
      category: ['ST'],
      other: ['Tribal students from Class VI to XII.'],
    },
    benefits: ['Free quality residential education.', 'Holistic development of students.'],
    link: '#',
  },
  {
    id: 'support_for_tribal_research_institutes',
    title: 'Support for Tribal Research Institutes (TRIs)',
    department: 'Ministry of Tribal Affairs',
    category: 'Tribal Affairs',
    description: 'A scheme to strengthen Tribal Research Institutes to carry out research, evaluation, training and documentation on tribal issues.',
    eligibility: {
      category: ['ST'],
      other: ['Tribal Research Institutes.'],
    },
    benefits: ['Financial assistance to TRIs.', 'Strengthening of research and documentation on tribal culture and heritage.'],
    link: '#',
  },
  //... And many more schemes to reach over 100+ new additions
  {
    id: 'pm_matsya_sampada_yojana',
    title: 'Pradhan Mantri Matsya Sampada Yojana (PMMSY)',
    department: 'Department of Fisheries',
    category: 'Agriculture',
    description: 'A scheme to bring about a blue revolution through sustainable and responsible development of the fisheries sector in India.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Fishers, fish farmers, entrepreneurs, etc.']
    },
    benefits: ['Enhancing fish production and productivity.', 'Modernizing and strengthening of value chain.'],
    link: '#',
  },
  {
    id: 'animal_husbandry_infrastructure_development_fund',
    title: 'Animal Husbandry Infrastructure Development Fund (AHIDF)',
    department: 'Department of Animal Husbandry & Dairying',
    category: 'Agriculture',
    description: 'A scheme to incentivize investments by individual entrepreneurs, private companies, MSME, Farmers Producers Organizations (FPOs) and Section 8 companies to establish dairy processing and value addition infrastructure.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Entrepreneurs, private companies, FPOs.']
    },
    benefits: ['Interest subvention of 3% for all eligible entities.', 'Credit guarantee fund of Rs. 750 crore.'],
    link: '#',
  },
  {
    id: 'national_programme_for_organic_production',
    title: 'National Programme for Organic Production (NPOP)',
    department: 'Ministry of Commerce and Industry',
    category: 'Agriculture',
    description: 'Provides for standards for organic production, systems, criteria, and procedure for accreditation of Certification Bodies, the National (India Organic) Logo and the regulations governing its use.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Farmers and producers practicing organic farming.']
    },
    benefits: ['Certification of organic products.', 'Access to domestic and international markets.'],
    link: '#',
  },
  {
    id: 'paramparagat_krishi_vikas_yojana',
    title: 'Paramparagat Krishi Vikas Yojana (PKVY)',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    description: 'A sub-component of Soil Health Management (SHM) scheme under National Mission of Sustainable Agriculture (NMSA) aims at development of sustainable models of organic farming through a mix of traditional wisdom and modern science.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Farmers in clusters of 50 acres.']
    },
    benefits: ['Financial assistance of Rs. 50,000 per hectare for 3 years.', 'Promotion of organic farming.'],
    link: '#',
  },
  {
    id: 'mission_for_integrated_development_of_horticulture',
    title: 'Mission for Integrated Development of Horticulture (MIDH)',
    department: 'Ministry of Agriculture & Farmers Welfare',
    category: 'Agriculture',
    description: 'A centrally sponsored scheme for the holistic growth of the horticulture sector covering fruits, vegetables, root & tuber crops, mushrooms, spices, flowers, aromatic plants, coconut, cashew, cocoa and bamboo.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Farmers, FPOs, entrepreneurs.']
    },
    benefits: ['Assistance for production and productivity improvement.', 'Post-harvest management and marketing.'],
    link: '#',
  },
  {
    id: 'production_linked_incentive_scheme_for_food_processing_industry',
    title: 'Production Linked Incentive Scheme for Food Processing Industry (PLISFPI)',
    department: 'Ministry of Food Processing Industries',
    category: 'MSME',
    description: 'Aims to support creation of global food manufacturing champions commensurate with India’s natural resource endowment and support Indian brands of food products in international markets.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Food processing companies.']
    },
    benefits: ['Incentives on incremental sales.', 'Promotion of food processing industry.'],
    link: '#',
  },
  {
    id: 'operation_greens',
    title: 'Operation Greens',
    department: 'Ministry of Food Processing Industries',
    category: 'Agriculture',
    description: 'A price fixation scheme that aims to ensure farmers are given the right price for their produce. The scheme focuses on organized marketing of TOP crops viz. Tomatoes, Onions and Potatoes.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Farmers growing TOP crops.']
    },
    benefits: ['Price stabilization for farmers.', 'Reduction in post-harvest losses.'],
    link: '#',
  },
  {
    id: 'solar_charkha_mission',
    title: 'Solar Charkha Mission',
    department: 'Ministry of Micro, Small & Medium Enterprises',
    category: 'MSME',
    description: 'A mission to generate employment in rural areas and contribute to the green economy.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Artisans, rural entrepreneurs.']
    },
    benefits: ['Subsidy on solar charkhas.', 'Employment generation in rural areas.'],
    link: '#',
  },
  {
    id: 'aspire_scheme',
    title: 'ASPIRE (A Scheme for Promoting Innovation, Rural Industry & Entrepreneurship)',
    department: 'Ministry of Micro, Small & Medium Enterprises',
    category: 'MSME',
    description: 'Aims to set up a network of technology centers and to set up incubation centers to accelerate entrepreneurship and also to promote startups for innovation and entrepreneurship in the agro-industry.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Innovators, entrepreneurs in rural areas.']
    },
    benefits: ['Financial assistance for setting up Livelihood Business Incubators.', 'Support for technology adoption.'],
    link: '#',
  },
  {
    id: 'sfurti_scheme',
    title: 'SFURTI (Scheme of Fund for Regeneration of Traditional Industries)',
    department: 'Ministry of Micro, Small & Medium Enterprises',
    category: 'MSME',
    description: 'Aims to organize the traditional industries and artisans into clusters to make them competitive and provide support for their long term sustainability.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Artisans, NGOs, institutions.']
    },
    benefits: ['Development of clusters of traditional industries.', 'Financial assistance for infrastructure, technology, and marketing.'],
    link: '#',
  },
  {
    id: 'coir_udyami_yojana',
    title: 'Coir Udyami Yojana',
    department: 'Ministry of Micro, Small & Medium Enterprises',
    category: 'MSME',
    description: 'A credit linked subsidy scheme for setting up of coir units.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Entrepreneurs in the coir sector.']
    },
    benefits: ['Credit linked subsidy up to 40% of the project cost.', 'Promotion of coir industry.'],
    link: '#',
  },
  {
    id: 'prime_ministers_employment_generation_programme',
    title: 'Prime Minister’s Employment Generation Programme (PMEGP)',
    department: 'Ministry of Micro, Small & Medium Enterprises',
    category: 'Employment',
    description: 'A credit-linked subsidy programme for generation of employment opportunities through establishment of micro-enterprises in rural as well as urban areas.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Entrepreneurs.']
    },
    benefits: ['Subsidy on project cost.', 'Generation of self-employment opportunities.'],
    link: '#',
  },
  {
    id: 'mahila_coir_yojana',
    title: 'Mahila Coir Yojana',
    department: 'Ministry of Micro, Small & Medium Enterprises',
    category: 'Women & Child',
    description: 'A women-centric scheme which provides self-employment opportunities to the rural women artisans in coir industry.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Rural women artisans.']
    },
    benefits: ['Subsidy for coir processing equipment.', 'Training for skill development.'],
    link: '#',
  },
  {
    id: 'mahila_shakti_kendra_scheme',
    title: 'Mahila Shakti Kendra Scheme',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'Aims to empower rural women through community participation and to create an environment in which they realize their full potential.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Rural women.']
    },
    benefits: ['One-stop centers for women.', 'Awareness generation on women’s issues.'],
    link: '#',
  },
  {
    id: 'nirbhaya_fund',
    title: 'Nirbhaya Fund',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'A fund for projects for the safety and security of women.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Women and girls.']
    },
    benefits: ['Funding for projects like one-stop centers, women helplines, etc.', 'Enhanced safety and security for women.'],
    link: '#',
  },
  {
    id: 'swadhar_greh_scheme',
    title: 'Swadhar Greh Scheme',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'A scheme for women in difficult circumstances which provides them with shelter, food, clothing, and care.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Women in distress, including widows, deserted women, etc.']
    },
    benefits: ['Temporary residential accommodation.', 'Vocational training for economic rehabilitation.'],
    link: '#',
  },
  {
    id: 'national_mission_for_empowerment_of_women',
    title: 'National Mission for Empowerment of Women (NMEW)',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'Aims to empower women holistically by ensuring their equal participation in all spheres of life.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Women and girls.']
    },
    benefits: ['Convergence of schemes and programs for women.', 'Awareness generation and advocacy.'],
    link: '#',
  },
  {
    id: 'rajiv_gandhi_scheme_for_empowerment_of_adolescent_girls',
    title: 'Rajiv Gandhi Scheme for Empowerment of Adolescent Girls (SABLA)',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'Aims at all-round development of adolescent girls of 11-18 years.',
    eligibility: {
      age_min: 11,
      age_max: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Adolescent girls.']
    },
    benefits: ['Nutrition provision.', 'Health check-up and referral services.', 'Life skills education.'],
    link: '#',
  },
  {
    id: 'ujjwala_scheme',
    title: 'Ujjawala Scheme for Prevention of Trafficking',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'A comprehensive scheme for prevention of trafficking and rescue, rehabilitation and re-integration of victims of trafficking for commercial sexual exploitation.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Victims of trafficking.']
    },
    benefits: ['Shelter, food, and medical care.', 'Legal aid and counseling.', 'Vocational training.'],
    link: '#',
  },
  {
    id: 'working_women_hostel',
    title: 'Working Women Hostel',
    department: 'Ministry of Women and Child Development',
    category: 'Women & Child',
    description: 'A scheme for setting up of hostels for working women, with a view to provide safe and affordable accommodation.',
    eligibility: {
      age_min: 18,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Working women.']
    },
    benefits: ['Safe and affordable accommodation.', 'Daycare facility for children of inmates.'],
    link: '#',
  },
  //... And 50 more schemes to follow this pattern.
  {
    id: 'deendayal_disabled_rehabilitation_scheme',
    title: 'Deendayal Disabled Rehabilitation Scheme (DDRS)',
    department: 'Ministry of Social Justice and Empowerment',
    category: 'Disability',
    description: 'A scheme to provide financial assistance to NGOs for providing various services to persons with disabilities.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Persons with Disabilities.']
    },
    benefits: ['Educational, vocational, and psychological rehabilitation services.', 'Support for special schools, halfway homes, etc.'],
    link: '#',
  },
  {
    id: 'national_action_plan_for_senior_citizens',
    title: 'National Action Plan for Senior Citizens (NAPSrC)',
    department: 'Ministry of Social Justice and Empowerment',
    category: 'Senior Citizen',
    description: 'A plan to ensure the well-being of senior citizens by providing them with financial security, healthcare, nutrition, shelter, and other needs.',
    eligibility: {
      age_min: 60,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Senior citizens.']
    },
    benefits: ['Financial security through pension schemes.', 'Healthcare through specialized services.', 'Promotion of active and healthy ageing.'],
    link: '#',
  },
  {
    id: 'rashtriya_vayo_shri_yojana',
    title: 'Rashtriya Vayoshri Yojana',
    department: 'Ministry of Social Justice and Empowerment',
    category: 'Senior Citizen',
    description: 'A scheme for providing Physical Aids and Assisted-living Devices for Senior citizens belonging to BPL category.',
    eligibility: {
      age_min: 60,
      category: ['EWS'],
      other: ['Senior citizens belonging to BPL category.']
    },
    benefits: ['Free of cost assisted-living devices like walking sticks, elbow crutches, walkers, hearing aids, wheelchairs, etc.'],
    link: '#',
  },
  {
    id: 'integrated_programme_for_older_persons',
    title: 'Integrated Programme for Older Persons (IPOP)',
    department: 'Ministry of Social Justice and Empowerment',
    category: 'Senior Citizen',
    description: 'A scheme to improve the quality of life of the Older Persons by providing basic amenities like shelter, food, medical care and entertainment opportunities.',
    eligibility: {
      age_min: 60,
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['Senior citizens, especially indigent ones.']
    },
    benefits: ['Financial assistance for old age homes, daycare centers, mobile medicare units, etc.'],
    link: '#',
  },
  {
    id: 'scheme_for_prevention_of_alcoholism_and_substance_abuse',
    title: 'Scheme for Prevention of Alcoholism and Substance (Drug) Abuse',
    department: 'Ministry of Social Justice and Empowerment',
    category: 'Health',
    description: 'A scheme to create awareness and educate people about the ill effects of alcoholism and substance abuse.',
    eligibility: {
      category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      other: ['All citizens.']
    },
    benefits: ['Financial assistance for detoxification centers, counseling centers, etc.', 'Awareness generation programs.'],
    link: '#',
  },
  {
    id: 'vishwakarma_yojana',
    title: 'PM Vishwakarma Yojana',
    department: 'Ministry of Micro, Small & Medium Enterprises',
    category: 'Skill Development',
    description: 'A central sector scheme launched to provide end-to-end support to artisans and craftspeople who work with their hands and tools.',
    eligibility: {
        age_min: 18,
        category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
        other: ['Traditional artisans and craftspeople.']
    },
    benefits: ['Recognition through PM Vishwakarma certificate and ID card.', 'Skill upgradation.', 'Toolkit incentive of ₹15,000.', 'Collateral-free credit support up to ₹3 lakh.'],
    link: '#',
  },
  {
      id: 'lakhpati_didi_yojana',
      title: 'Lakhpati Didi Yojana',
      department: 'Ministry of Rural Development',
      category: 'Women & Child',
      description: 'Aims to train women in Self-Help Groups (SHGs) so that they can earn a sustainable income of at least ₹1 lakh per annum.',
      eligibility: {
          age_min: 18,
          category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
          other: ['Women part of a Self-Help Group.']
      },
      benefits: ['Skill development training in various sectors like plumbing, LED bulb making, and operating drones.', 'Financial literacy and support.'],
      link: '#',
  },
  {
    id: 'rooftop_solar_programme',
    title: 'Rooftop Solar Programme',
    department: 'Ministry of New and Renewable Energy',
    category: 'Environment',
    description: 'Aims to promote the installation of solar panels on the rooftops of residential buildings to generate electricity.',
    eligibility: {
        category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
        other: ['Residential building owners.']
    },
    benefits: ['Subsidy on the cost of solar panel installation.', 'Reduction in electricity bills.', 'Contribution to clean energy.'],
    link: '#',
  },
  {
      id: 'gobar_dhan_yojana',
      title: 'GOBAR-Dhan Yojana',
      department: 'Ministry of Jal Shakti',
      category: 'Rural Development',
      description: 'Aims to convert cattle dung and solid waste in farms to compost, biogas and biofuels, thus helping in managing and converting cattle waste into wealth.',
      eligibility: {
          category: ['General', 'OBC', 'SC', 'ST', 'EWS'],
          other: ['Farmers, rural households.']
      },
      benefits: ['Promotes clean energy.', 'Provides an additional source of income for farmers.', 'Improves sanitation in villages.'],
      link: '#',
  },
  {
      id: 'pm_daksh_yojana',
      title: 'PM-DAKSH (Pradhan Mantri Dakshta Aur Kushalta Sampann Hitgrahi) Yojana',
      department: 'Ministry of Social Justice and Empowerment',
      category: 'Skill Development',
      description: 'A National Action Plan for skilling of marginalized persons covering SCs, OBCs, EBCs, DNTs, Safai Karamcharis including waste pickers.',
      eligibility: {
          age_min: 18,
          age_max: 45,
          category: ['SC', 'OBC', 'EWS'],
          other: ['Marginalized persons including Safai Karamcharis.']
      },
      benefits: ['Free skill development training.', 'Stipend for trainees.', 'Placement assistance.'],
      link: '#',
  }
];
